
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/proj-courses-w24-5pm-4
owner: ucsb-cs156-w24
repo_name: proj-courses-w24-5pm-4
pull_requests: [{"author":{"id":"U_kgDOB7tbUw","is_bot":false,"login":"Torry051","name":"Rui Tong"},"headRefName":"rt-PSErrorMessage","number":35,"title":"FEATURE: More descriptive error message on personal schedule","url":"https://github.com/ucsb-cs156-w24/proj-courses-w24-5pm-4/pull/35"},{"author":{"id":"U_kgDOBdHvhQ","is_bot":false,"login":"anirudhiyer1","name":""},"headRefName":"Anirudh-SimplifyPSSchedule","number":34,"title":"REFACTOR: Simplify \"Personal schedule\" navigation","url":"https://github.com/ucsb-cs156-w24/proj-courses-w24-5pm-4/pull/34"},{"author":{"id":"MDQ6VXNlcjMzMDQxMTU0","is_bot":false,"login":"ColeFoster08","name":"Cole Foster"},"headRefName":"Cole-Proj-FrontendUpdateCoursesInRange","number":32,"title":"FEATURE: Add frontend for job to update all courses in a range of quarters","url":"https://github.com/ucsb-cs156-w24/proj-courses-w24-5pm-4/pull/32"},{"author":{"id":"U_kgDOB7tbUw","is_bot":false,"login":"Torry051","name":"Rui Tong"},"headRefName":"rt-PSCourseDescription2","number":28,"title":"FEATURE: More descriptive personal courses page","url":"https://github.com/ucsb-cs156-w24/proj-courses-w24-5pm-4/pull/28"},{"author":{"id":"U_kgDOB2-3Pg","is_bot":false,"login":"samanthwest","name":""},"headRefName":"sw---descriptions","number":27,"title":"FEATURE: Add course description to course details page","url":"https://github.com/ucsb-cs156-w24/proj-courses-w24-5pm-4/pull/27"},{"author":{"id":"U_kgDOBXuxxw","is_bot":false,"login":"Cory-Zhao","name":"Cory Zhao"},"headRefName":"CZ-PersonalSchedules-quarter","number":23,"title":"BUG: Personal Schedules Update not updating the Quarter field","url":"https://github.com/ucsb-cs156-w24/proj-courses-w24-5pm-4/pull/23"},{"author":{"id":"U_kgDOBXuxxw","is_bot":false,"login":"Cory-Zhao","name":"Cory Zhao"},"headRefName":"CZ-PersonalSchedules-edit","number":18,"title":"FEATURE: Add edit page for personal schedules","url":"https://github.com/ucsb-cs156-w24/proj-courses-w24-5pm-4/pull/18"}]
